-- AlterTable
ALTER TABLE "Restaurant" ADD COLUMN     "aberto" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "aceitaCartaoCredito" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "aceitaCartaoDebito" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "aceitaDinheiro" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "aceitaEntrega" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "aceitaMesa" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "aceitaPixPresencial" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "aceitaRetirada" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "asaasSubscriptionId" TEXT,
ADD COLUMN     "bairrosAtendidos" JSONB,
ADD COLUMN     "banner" TEXT,
ADD COLUMN     "businessHours" JSONB,
ADD COLUMN     "chavePix" TEXT,
ADD COLUMN     "corPrimaria" TEXT DEFAULT '#16a34a',
ADD COLUMN     "customDomain" TEXT,
ADD COLUMN     "customDomainStatus" TEXT DEFAULT 'PENDING',
ADD COLUMN     "customDomainVerified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "emailSuporte" TEXT,
ADD COLUMN     "ga4MeasurementId" TEXT,
ADD COLUMN     "gtmId" TEXT,
ADD COLUMN     "horarioAbertura" TEXT,
ADD COLUMN     "horarioFechamento" TEXT,
ADD COLUMN     "logo" TEXT,
ADD COLUMN     "loyaltyEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "loyaltyPointsPerBrl" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "loyaltyRedeemRate" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "mensagemEntrega" TEXT,
ADD COLUMN     "mensagemFechado" TEXT,
ADD COLUMN     "metaAccessToken" TEXT,
ADD COLUMN     "metaPixelId" TEXT,
ADD COLUMN     "mostrarPrecos" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "nomePlataforma" TEXT,
ADD COLUMN     "notifEmailNewOrder" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "npsDaysAfterOrder" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "npsEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "pausaAbertura" TEXT,
ADD COLUMN     "pausaAtiva" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "pausaFechamento" TEXT,
ADD COLUMN     "pedidoMinimoEntregaGratis" DOUBLE PRECISION,
ADD COLUMN     "plan" TEXT NOT NULL DEFAULT 'FREE',
ADD COLUMN     "raioEntregaKm" DOUBLE PRECISION,
ADD COLUMN     "subscriptionStatus" "SubscriptionStatus" NOT NULL DEFAULT 'TRIAL',
ADD COLUMN     "taxaEntrega" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "tempoEstimadoEntrega" TEXT,
ADD COLUMN     "textoBoasVindas" TEXT,
ADD COLUMN     "textoRodape" TEXT,
ADD COLUMN     "trialEndsAt" TIMESTAMP(3),
ADD COLUMN     "urlPublica" TEXT,
ADD COLUMN     "whatsapp" TEXT,
ADD COLUMN     "whatsappSuporte" TEXT,
ADD COLUMN     "wppEnvioAutomatico" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "wppMsgConfirmado" TEXT,
ADD COLUMN     "wppMsgPedido" TEXT,
ADD COLUMN     "wppMsgPronto" TEXT,
ADD COLUMN     "wppMsgSaiu" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX "Restaurant_customDomain_key" ON "Restaurant"("customDomain");

-- CreateIndex
CREATE INDEX "Restaurant_slug_idx" ON "Restaurant"("slug");

-- CreateIndex
CREATE INDEX "Restaurant_customDomain_idx" ON "Restaurant"("customDomain");
