CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'RESTAURANT');

ALTER TABLE "User"
ADD COLUMN "role" "UserRole" NOT NULL DEFAULT 'RESTAURANT',
ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "plan" TEXT NOT NULL DEFAULT 'FREE',
ADD COLUMN "subscriptionStatus" TEXT NOT NULL DEFAULT 'TRIAL',
ADD COLUMN "trialEndsAt" TIMESTAMP(3);
