http:
  routers:
    frontend-https:
      rule: "Host(`cardapiopedeai.com.br`) || Host(`www.cardapiopedeai.com.br`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: frontend

    frontend-http:
      rule: "Host(`cardapiopedeai.com.br`) || Host(`www.cardapiopedeai.com.br`)"
      entryPoints:
        - web
      service: frontend

    backend-https:
      rule: "Host(`api.cardapiopedeai.com.br`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: backend

    backend-http:
      rule: "Host(`api.cardapiopedeai.com.br`)"
      entryPoints:
        - web
      service: backend

    backend-path-https:
      rule: "Host(`cardapiopedeai.com.br`) && PathPrefix(`/api`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - strip-api
      service: backend

    backend-path-http:
      rule: "Host(`cardapiopedeai.com.br`) && PathPrefix(`/api`)"
      entryPoints:
        - web
      middlewares:
        - strip-api
      service: backend

  middlewares:
    strip-api:
      stripPrefix:
        prefixes:
          - /api

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"

    backend:
      loadBalancer:
        servers:
          - url: "http://backend:3000"
