ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gtmId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "ga4MeasurementId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "metaPixelId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "metaAccessToken" TEXT;
